travis:
  secure:
    BINSTAR_TOKEN: aSyjROzR6LSob8ljgZVFot0fDFey9S6NHUI+8bpnH1ElCL2oJYaXKbAl6T4QOa4WQ/0ZcXw6v1e+bkMDpvI0dQE2SJCZqAXm45yJLwNSIPnJKkjKmcoVYMpZWtUGVR6iEExVmJ98pjRZqMyWUATE0Fn0gzSeuWC57EHnaObPkoy50Z1nbLR5bJ27mwwJ0oU7WzGW9MYHIdzO/TcVHm5y0RGpl4c96bfcbT89ef2h6ViA0l7Pd6fjgeox0pXh2+VZzZu0TuK7rR17IkU5YjoqmqexQlPtLJTsNvVKZgaFul0f9l/OwC/derVQje1BdVs8D4Cu9//50zZGk7o4+5e2AZmhvoIoHrZeqxEy9Iz19zYowClJbxJbKoJxonTOitSsKrNcpUyXZm1V6alxxd8dkqGIgz+osdSYSCn6mZSVfYHgLVhkNwVJfbYrunWidKR0836OBS5ZEbbvD72toRUryyafeqHlbP6Dum2/+2nQUhzphGbwxZDSZ5ERi/kngNaIEteK/Wj6pQUSZSG2JF1mrp1tSs1R7Mudu0S9h8mH2vwmJS0AyuDViQpIoedqm3x/3F0YBIS01E+2pnSR67hzzqmHOfy6TeVLcicobhX9kF00VsZbDi7sYhKSGwcORWyklP9fcTZQv5Ocw6utz2NyPuzDCGl5R7Ykd9dEFH0sBgA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
